# Generated by Django 3.2.9 on 2021-12-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoenixgram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='like',
            field=models.IntegerField(blank=True),
        ),
    ]
