# Generated by Django 3.2.9 on 2021-12-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoenixgram', '0002_auto_20211204_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
